// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbypedcyszozqezowbbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieXBlZGN5c3pvenFlem93YmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzY0MjcsImV4cCI6MjA2MjA1MjQyN30.hrurSWgeuPI2uaM4SE8qf_m7GQxSK8lr4WY1KlRukp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);